### PR TITLE
fix: German localisation

### PR DESCRIPTION
**Pull request by Ceeee**
There were many "dictionary mistakes" in that localisation. I (German native speaker) fixed things for better comprehension and a more natural/idiomatic structure.

### CODE REVIEW

**Comment by GunshipPenguin** [comment]
Ran this by a German speaking friend, he said it looks good, but suggested changing endgame_win_text to "Sie haben das Spielbrett in %d Zügen überschwommen." since your changes got rid of the verb "flood" in that string. Thoughts?

**Comment by ZeroZirq** [comment]
I think "fluteten" is the right word for it. I'm from Germany, too and if needed i would write u another Translation. 
e.g. i think u can replace "Samen" and use "Seeds" again, because its also known in Germany.
also its maybe better to say "Persönliche Bestleistung für diesen Bretttyp: %d Züge"
Just write again if you want my help.
Sincerly, ZeroZirq

P.S.: Big Fan, nice work :+1:

**Comment by GunshipPenguin** [comment]
@ZeroZirq 

Not sure if @Ceeee is going to respond to my suggestion and I think that what you said especially about using the English word "Seed" is valid. If you could edit the translations file to make it sound more natural and open a new PR, I'll get it looked over again and merge it instead of this one.

**Comment by ZeroZirq** [comment]
I try it. Hope i understand it in the right way.
[Openflood_Übersetzung.txt](https://github.com/GunshipPenguin/open_flood/files/477584/Openflood_Ubersetzung.txt)

**Comment by GunshipPenguin** [comment]
@ZiroZirq, could you open a new PR for your translation please?

**Comment by mueller-ma** [comment]
I created #22

**Comment by Ceeee** [comment]
Sorry for the delay, but yes I don't log in here much :-D

There is no such word as "überschwommen", I'm afraid. (You're friend is not a native I suppose?) The verb "fluten" is possible but if you are after something natural sounding, I don't think that qualifies. German does not use the verb fluten/flood in the context of a flood fill with colour, so it's not a good translation to have it.

And yes, seed is known as a jargon word in computer science, esp. in cryptography, but I wouldn't consider it common place. "Samen" definitely conjures different connotations I don't think it's a possible choice. That's why I used "Saat" instead.

The file posted by ghost contains many of the original mistakes again. I'd find it quite frustrating if that was the outcome of my work here. There are very essential mistakes like wrong conjugations, that someone speaking German natively wouldn't make. 

I'm dealing with translations in a professional context and literal choices are usually the worst when it comes to quality ;-)

**Comment by mueller-ma** [comment]
@Ceeee "überschwommen" is past form of "überschwemmen": http://www.duden.de/rechtschreibung/ueberschwemmen

**Comment by Ceeee** [comment]
Proposal: Maybe you should actually _read_ the articles that you link to? - Before you post, I mean. xD
Quote: "überschwemmen (schwaches Verb)" (weak verb); "Prätertium Singular: ich überschwemmte"

I repeat: The word "überschwommen" does not exist. And the link you gave confirms that. (For non-German speakers try and do a page search for the 'word' in question - not in there.)

Plus "überschwemmen" (in whatever form) is a bad translation for flooded here, as you don't use the verb in that sense when talking about colour in German. Nor do you with the verb "fluten". In both cases it is a literal translation and as such it is bad one.

**Comment by GunshipPenguin** [comment]
@Ceeee what you're saying makes sense. The friend I ran my translations by is not a native speaker so I guess he just made a mistake with überschwommen. I'll merge this PR and do a release. 

A large share of the people using Open Flood are German speaking and I'm sure that this will improve the game for them, so thanks very much for the improvements.

Thanks also to @mueller-ma for your input and other PR.

**Comment by Ceeee** [comment]
Cool. Thanks. I'm looking forward to playing the latest release of one of my favourite casual FOSS games! And glad I could contribute with a trifle.

**Pull request merged**
